<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MdcAi.OpenAiApi\MdcAi.OpenAiApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="Newtonsoft.Json" />
    <Using Include="Newtonsoft.Json.Linq" />
    <Using Include="MdcAi.OpenAiApi" />
    <Using Include="MdcAi.ChatCore.Sessions" />
    <Using Include="MdcAi.ChatCore.Tools" />
    <Using Include="MdcAi.ChatCore.Security" />
    <Using Include="MdcAi.ChatCore.Prompting" />
  </ItemGroup>

</Project>
