// <auto-generated />
using System;
using MdcAi.ChatUI.LocalDal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MdcAi.ChatUI.LocalDal.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20260831102241_AgenticPhase3BackgroundJobs")]
    partial class AgenticPhase3BackgroundJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbBackgroundJob", b =>
                {
                    b.Property<string>("IdJob")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtifactId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandPresentationHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT");

                    b.Property<long?>("OutputBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OutputTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerTurnId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdJob");

                    b.HasIndex("OwnerConversationId");

                    b.HasIndex("Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbCategory", b =>
                {
                    b.Property<string>("IdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconGlyph")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCategory");

                    b.HasIndex("IdSettings");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = "default",
                            Description = "General Purpose AI Assistant",
                            IdSettings = "general",
                            IsTrash = false,
                            Name = "General"
                        });
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatSettings", b =>
                {
                    b.Property<string>("IdSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FrequencyPenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Premise")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PresencePenalty")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Streaming")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopP")
                        .HasColumnType("TEXT");

                    b.HasKey("IdSettings");

                    b.ToTable("ChatSettings");

                    b.HasData(
                        new
                        {
                            IdSettings = "general",
                            FrequencyPenalty = 1m,
                            Model = "gpt-4o",
                            Premise = "You are a helpful but cynical and humorous assistant (but not over the top). You give short and straight to the point answers.",
                            PresencePenalty = 1m,
                            Streaming = true,
                            Temperature = 1m,
                            TopP = 1m
                        });
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatStep", b =>
                {
                    b.Property<string>("IdStep")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextPlanJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DecodeDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedTs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstDeltaTs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstOutputTs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstTokenLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdTurn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptCacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptCacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedTs")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdStep");

                    b.HasIndex("IdTurn", "StepNumber")
                        .IsUnique();

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatTurn", b =>
                {
                    b.Property<string>("IdTurn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedTs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GoalRevision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoalRound")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdConversation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdGoal")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTriggerMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSectionsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("StepCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolsSchemaSnapshot")
                        .HasColumnType("TEXT");

                    b.HasKey("IdTurn");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdTriggerMessage");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbConversation", b =>
                {
                    b.Property<string>("IdConversation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdSettingsOverride")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ToolsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasColumnType("TEXT");

                    b.HasKey("IdConversation");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdSettingsOverride");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbMessage", b =>
                {
                    b.Property<string>("IdMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinishReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdConversation")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdMessageParent")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTurn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reasoning")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningDetailsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningRawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceInStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdConversation");

                    b.HasIndex("IdStep");

                    b.HasIndex("IdTurn");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbModelRequestAttempt", b =>
                {
                    b.Property<string>("IdAttempt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureDetail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTurn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetryDelayFromHeader")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryDisposition")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetryPolicyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RetryStartedTs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduledDelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("IdAttempt");

                    b.HasIndex("IdStep", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("ModelRequestAttempts");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbToolCall", b =>
                {
                    b.Property<string>("IdToolCall")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArgumentsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CallIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallPresentationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdAssistantMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdStep")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTurn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProposedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultPresentationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Risk")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedTs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasColumnType("TEXT");

                    b.HasKey("IdToolCall");

                    b.HasIndex("IdAssistantMessage", "CallIndex")
                        .IsUnique();

                    b.HasIndex("IdAssistantMessage", "ToolCallId")
                        .IsUnique();

                    b.ToTable("ToolCalls");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbCategory", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatSettings", "Settings")
                        .WithMany()
                        .HasForeignKey("IdSettings")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatStep", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatTurn", "Turn")
                        .WithMany("Steps")
                        .HasForeignKey("IdTurn")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatTurn", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbConversation", null)
                        .WithMany("Turns")
                        .HasForeignKey("IdConversation");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbConversation", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbCategory", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory");

                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatSettings", "SettingsOverride")
                        .WithMany()
                        .HasForeignKey("IdSettingsOverride");

                    b.Navigation("Category");

                    b.Navigation("SettingsOverride");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbMessage", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("IdConversation");

                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatStep", "Step")
                        .WithMany("Messages")
                        .HasForeignKey("IdStep");

                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatTurn", "Turn")
                        .WithMany("Messages")
                        .HasForeignKey("IdTurn");

                    b.Navigation("Conversation");

                    b.Navigation("Step");

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbModelRequestAttempt", b =>
                {
                    b.HasOne("MdcAi.ChatUI.LocalDal.DbChatStep", "Step")
                        .WithMany("Attempts")
                        .HasForeignKey("IdStep")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Step");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatStep", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbChatTurn", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MdcAi.ChatUI.LocalDal.DbConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
