//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdcAi.ChatUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class GlobalChatSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GlobalChatSettings defaultInstance = ((GlobalChatSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GlobalChatSettings())));
        
        public static GlobalChatSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGettingStartedConvoTip {
            get {
                return ((bool)(this["ShowGettingStartedConvoTip"]));
            }
            set {
                this["ShowGettingStartedConvoTip"] = value;
            }
        }
    }
}
